### ISSUE TITLE
Build interactive plots with Shiny or Steamlit

### ISSUE THREAD

**Issue by abearab** [GilbertLabUCSF/DDRi-screens#1]
- [x] Build interactive volcano plots using [screenpro/dashboard](https://github.com/ArcInstitute/ScreenPro2/blob/master/screenpro/dashboard/__init__.py) module and save as html files – @abearab 
- [x] Build streamlit app as a wrapper to show bokeh plots – @abearab 
____
- https://streamlit.io/
- ~https://shiny.rstudio.com/py/~
- https://docs.kanaries.net/topics/Streamlit/streamlit-vscode

**Comment by abearab** [comment]
@nick-youngblut 

Hi Nick, Thanks for joining this repo! ~In these two notebooks I tried to integrate majority of datasets we have for this project [`0-data-gathering.ipynb`](https://github.com/GilbertLabUCSF/DDRi/blob/main/0-data-gathering.ipynb), [`1-correlations.ipynb`](https://github.com/GilbertLabUCSF/DDRi/blob/main/1-correlations.ipynb). I tried to use [@abearab/ScreenPro2](https://github.com/abearab/ScreenPro2) for this part although that is originally processed through [@mhorlbeck/ScreenProcessing](https://github.com/mhorlbeck/ScreenProcessing) pipeline.~

I think it will be wonderful if we can have a data dashboard similar to https://crisprbrain.org/simple-screen.

**Comment by nick-youngblut** [comment]
Thanks for sharing the info! A dashboard similar to CRISPRBrain should be doable

**Comment by abearab** [comment]
Hi @nick-youngblut, I drafted an script to build streamlit app using interactive plots I created with ScreenPro2. Can we get your help to deploy it?

<img width="1509" alt="image" src="https://github.com/user-attachments/assets/3f19fc59-246b-4fbc-a7f1-44718c92d792" />

or a newer version :)

![image](https://github.com/user-attachments/assets/7855803f-1fb4-4ad2-9a43-a8e6bc23a48c)
